export * from './topBanner';
export * from './discounts';
export * from './discountBanner';
export * from './categories';
export * from './amazingOffer';
export * from './bestSeller';
export * from './bottomBanner';
export * from './home';
export * from './api';
